name: telegram message
on: 
  issue_comment:
    types: created
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  pull_request_review_comment:
    types: created
  push:
    
jobs:

  build:
    name: Notifier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: ${{ github.event_name }} from ${{ github.actor }}. (${{ job.status }}) (${{ github.event_path }})
